### PR TITLE
change default local planner

### PR DESCRIPTION
**Pull request by y-shiigi**
Present local planner can't avoid new obstacle not registered in the map(ex. person) .Teb Local Planner  works well. Can you try this ? @taichiH @sasabot 

In this settings, robot run as non-holonomic. You can change the parameter with reference to 
[Tutorial](http://wiki.ros.org/teb_local_planner/Tutorials/Planning%20for%20holonomic%20robots). However, I don't like this movement, especially when going straight.

This PR has some conflicts with https://github.com/seed-solutions/aero-ros-pkg/pull/382 , but it's written based on master branch because of [WIP]. sorry.

### CODE REVIEW

**Comment by taichiH** [comment]
@y-shiigi We have same experince as you said when using eband_local_planner. So I tested other planner, base_local_planner and dwa_local_planner. I'm using dwa_local_planner now. I copied and pasted all settings of move_base from jsk_pr2_move_base (https://github.com/jsk-ros-pkg/jsk_robot/tree/master/jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_move_base) include local and global costmap parameters because parameter setting was very hard. Robot behaiver change significantly if you change move_base parameters even for just a bit.
In my opinion, We should change default local planner because, default planner should not has trouble. Although I'm using dwa_local_planner, I cannot recommend this planner because robot behaiver is little bit weird. Robot often look sideway when go straight. 
I'll try teb_local_planner and add comment after try it.

**Comment by taichiH** [comment]
This is not serious problem.
>However, I don't like this movement, especially when going straight.

>I cannot recommend this planner because robot behaiver is little bit weird. Robot often look sideway when go straight.

This is serious problem that we have to fix.
>Present local planner can't avoid new obstacle not registered in the map(ex. person) .

**Comment by hyaguchi947d** [comment]
Hello,

I agree @sasabot to keep default local planner.
In the last year I met the problem about DWAPlanner and it doesn't work correctly with omni wheel because it is for Differential Wheel.
This is why we changed the default planner.
It is better to make a easy way to change local / global planner, keeping default one.

Thanks.

**Comment by taichiH** [comment]
I add local planner options for multiple users on https://github.com/y-shiigi/aero-ros-pkg/pull/1 .
Users can choose planner to suit your environment.

**Comment by y-shiigi** [comment]
@sasabot 
>what about the costmap_common.yaml?
doesn't this change depending on the planner? or does it only rely on the setting?
any good way to make these files optional?

It doesn't rely on the planner, as far as I verified.

>also, there should be an update in readme explaining when to use which planner

I update README. please check.

**Pull request merged**
